### ISSUE TITLE
can't bookmark with OC 8.0.5

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/bookmarks#186]
I can't save the following bookmark:

URL: http://www.unixmen.com/configure-linux-clients-authenticate-using-openldap/
Title: How To Configure Linux Clients To Authenticate Using OpenLDAP | Unixmen

in owncloud.log I can see the following error:

```
{"reqId":"9cf5154fbebf833030a148e24d1d0bb3","remoteAddr":"192.168.99.10","app":"index","message":"Exception: {\"Message\":\"An exception occurred while executing '\\n\\t\\t\\tINSERT INTO \\\"oc_bookmarks\\\"\\n\\t\\t\\t(\\\"url\\\", \\\"title\\\", \\\"user_id\\\", \\\"public\\\", \\\"added\\\", \\\"lastmodified\\\", \\\"description\\\")\\n\\t\\t\\tVALUES (?, ?, ?, ?, cast(extract(epoch from current_timestamp) as integer), cast(extract(epoch from current_timestamp) as integer), ?)\\n\\t\\t\\t' with params [\\\"http:\\\\\\\/\\\\\\\/www.unixmen.com\\\\\\\/configure-linux-clients-authenticate-using-openldap\\\\\\\/\\\", \\\"How To Configure Linux Clients To Authenticate Using OpenLDAP | Unixmen<\\\\\\\/title><meta http-equiv=\\\\\\\"Content-Type\\\\\\\" content=\\\\\\\"text\\\\\\\/html; charset=UTF-8\\\\\\\" \\\\\\\/><meta name=\\\\\\\"viewport\\\\\\\" content=\\\\\\\"width=device-width, initial-scale=1.0\\\\\\\"><title>How To Configure Linux Clients To Authenticate Using OpenLDAP | Unixmen\\\", \\\"myuser\\\", 0, \\\"test\\\"]:\\n\\nSQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(140)\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), '\\\\n\\\\t\\\\t\\\\tINSERT INTO...', Array)\\n#2 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/lib\\\/private\\\/db\\\/statementwrapper.php(54): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/apps\\\/bookmarks\\\/controller\\\/lib\\\/bookmarks.php(469): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/apps\\\/bookmarks\\\/controller\\\/rest\\\/bookmarkcontroller.php(84): OCA\\\\Bookmarks\\\\Controller\\\\Lib\\\\Bookmarks::addBookmark('myuser', Object(OC\\\\AppFramework\\\\Db\\\\Db), 'http:\\\/\\\/www.unix...', 'How To Configur...', Array, 'test', false)\\n#5 [internal function]: OCA\\\\Bookmarks\\\\Controller\\\\Rest\\\\BookmarkController->newBookmark('http:\\\/\\\/www.unix...', Array, 0, 'How To Configur...', false, 'test')\\n#6 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Bookmarks\\\\Controller\\\\Rest\\\\BookmarkController), 'newBookmark')\\n#8 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Bookmarks\\\\Controller\\\\Rest\\\\BookmarkController), 'newBookmark')\\n#9 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('BookmarkControl...', 'newBookmark', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/lib\\\/private\\\/route\\\/router.php(252): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/lib\\\/base.php(791): OC\\\\Route\\\\Router->match('\\\/apps\\\/bookmarks...')\\n#13 \\\/var\\\/www\\\/cloud.domain.tld.net\\\/index.php(36): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud.domain.tld.net\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91}","level":4,"time":"2015-08-02T18:13:20+00:00"}
```

**Comment by ege1** [comment]
Yes, that's a known bug [https://github.com/owncloud/bookmarks/issues/29]. I hope it gets fixed/merged soon...

**Comment by hostingnuggets** [comment]
My god that's from 2013, really hope it gets fixed soon! Thanks for the pointers.

**Comment by tflidd** [comment]
Is this still an issue? There have been a few fixes. If not, we could close this issue.

**Comment by hostingnuggets** [comment]
in the mean time i moved to Nextcloud, no issues with bookmarking there, i guess i will just close this issue
