### ISSUE TITLE
Android App clientProtocolException with OC 9.1 bookmark app

### ISSUE THREAD

**Issue by thinking-aloud** [owncloud/bookmarks#280]
### Steps to reproduce
Try to refresh bookmarks

### Expected behaviour
get the latest bookmarks from the server

### Actual behaviour
org.apache.http.client.clientProtocolException

### Server configuration
**Operating system**:
Ubuntu 16.04 armhf

**Web server:**
Apache 2.4.18

**Database:**
MariaDB 10.0.25

**PHP version:**
7.0.8

**ownCloud version:** (see ownCloud admin page)
9.1.0-1.1

**Bookmarks version:** (see ownCloud apps page)
0.8.1 (from stable9.1 branch)

**Updated from an older ownCloud or fresh install:**
updated from 9.0 ... I think

**Where did you install ownCloud from:**
official repositiory

**Signing status (ownCloud 9.0 and above):**
I have that disabled, because it always wines about changed memory limit in .htaccess

**List of activated apps:**
```
  - bookmarks: 0.8.1
  - calendar: 1.3.2
  - comments: 0.3.0
  - contacts: 1.3.1.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - news: 9.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
```

**The content of config/config.php:**
```
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc01015wu7p5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/lkarsten.de\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "integrity.check.disabled": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log
```
[Thu Aug 11 14:02:39.073515 2016] [core:notice] [pid 2166] AH00094: Command line: '/usr/sbin/apache2'
[Thu Aug 11 14:04:44.052706 2016] [mpm_prefork:notice] [pid 2166] AH00169: caught SIGTERM, shutting down
[Thu Aug 11 14:04:46.070706 2016] [mpm_prefork:notice] [pid 2451] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-fips configured -- resuming normal operations
[Thu Aug 11 14:04:46.070836 2016] [core:notice] [pid 2451] AH00094: Command line: '/usr/sbin/apache2'
[Thu Aug 11 14:05:02.684048 2016] [authz_core:error] [pid 2455] [client IP:46278] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Aug 11 14:06:03.362794 2016] [mpm_prefork:notice] [pid 2451] AH00169: caught SIGTERM, shutting down
[Thu Aug 11 14:06:05.259148 2016] [mpm_prefork:notice] [pid 2900] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-fips configured -- resuming normal operations
[Thu Aug 11 14:06:05.259284 2016] [core:notice] [pid 2900] AH00094: Command line: '/usr/sbin/apache2'
[Thu Aug 11 14:25:23.265924 2016] [authz_core:error] [pid 2946] [client IP:46644] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Thu Aug 11 14:25:48.793221 2016] [authz_core:error] [pid 2950] [client IP:46662] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"e\/j4X1IkSLV3+w1aV8O9","remoteAddr":"IP","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"Did expect one result but found none when executing: query \\\"SELECT `items`.* FROM `*PREFIX*news_items` `items` JOIN `*PREFIX*news_feeds` `feeds` ON `feeds`.`id` = `items`.`feed_id` AND `feeds`.`deleted_at` = 0 AND `feeds`.`user_id` = ? AND `items`.`id` = ? LEFT OUTER JOIN `*PREFIX*news_folders` `folders` ON `folders`.`id` = `feeds`.`folder_id` WHERE `feeds`.`folder_id` = 0 OR `folders`.`deleted_at` = 0 ORDER BY `items`.`id` DESC\\\"; parameters Array\\n(\\n    [0] => lennart\\n    [1] => 47847\\n)\\n; limit \\\"\\\"; offset \\\"\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(372): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT `items`....', Array, NULL, NULL)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/itemmapper.php(82): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT `items`....', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/mysql\\\/itemmapper.php(67): OCA\\\\News\\\\Db\\\\ItemMapper->find(47847, 'lennart')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/service\\\/itemservice.php(152): OCA\\\\News\\\\Db\\\\Mysql\\\\ItemMapper->readItem(47847, true, 1470826598, 'lennart')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/controller\\\/itemapicontroller.php(177): OCA\\\\News\\\\Service\\\\ItemService->read(47847, true, 'lennart')\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/controller\\\/itemapicontroller.php(193): OCA\\\\News\\\\Controller\\\\ItemApiController->setMultipleRead(true, Array)\\n#6 [internal function]: OCA\\\\News\\\\Controller\\\\ItemApiController->readMultiple(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\ItemApiController), 'readMultiple')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\ItemApiController), 'readMultiple')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\News\\\\\\\\Contro...', 'readMultiple', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/api\\\/...')\\n#14 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php\",\"Line\":288}","level":3,"time":"2016-08-10T10:56:38+00:00","method":"PUT","url":"\/owncloud\/index.php\/apps\/news\/api\/v1-2\/items\/read\/multiple","user":"lennart"}
{"reqId":"Hg1zfzNGPqPnRHVEfkTp","remoteAddr":"","app":"cron","message":"Call to undefined method OCA\\News\\Cron\\Updater::setId()","level":4,"time":"2016-08-10T20:00:01+00:00","method":"--","url":"--","user":"--"}
{"reqId":"KrGIMQlyugfDWvRfrX2x","remoteAddr":"","app":"cron","message":"Call to undefined method OCA\\News\\Cron\\Updater::setId()","level":4,"time":"2016-08-11T08:00:01+00:00","method":"--","url":"--","user":"--"}
{"reqId":"KszLrHd7eRMJgV3sUtfl","remoteAddr":"IP","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":84,\"User\":\"lennart\"}","level":4,"time":"2016-08-11T10:41:48+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"lennart"}
{"reqId":"Qei6YTIG490x042au+5U","remoteAddr":"IP","app":"PHP","message":"Undefined index: two-factor-providers at \/var\/www\/owncloud\/lib\/private\/Authentication\/TwoFactorAuth\/Manager.php#111","level":3,"time":"2016-08-11T10:49:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","user":"lennart"}
{"reqId":"Qei6YTIG490x042au+5U","remoteAddr":"IP","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/lib\/private\/Authentication\/TwoFactorAuth\/Manager.php#112","level":3,"time":"2016-08-11T10:49:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","user":"lennart"}
{"reqId":"lZ0LPiSBIOzCitWPGriN","remoteAddr":"IP","app":"PHP","message":"Undefined index: two-factor-providers at \/var\/www\/owncloud\/lib\/private\/Authentication\/TwoFactorAuth\/Manager.php#111","level":3,"time":"2016-08-11T10:49:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","user":"lennart"}
{"reqId":"lZ0LPiSBIOzCitWPGriN","remoteAddr":"IP","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/lib\/private\/Authentication\/TwoFactorAuth\/Manager.php#112","level":3,"time":"2016-08-11T10:49:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","user":"lennart"}
{"reqId":"Q8rKKExb8XogwrCGPium","remoteAddr":"IP","app":"core","message":"starting upgrade from 9.1.0.15 to 9.1.0.15","level":0,"time":"2016-08-11T10:53:56+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=OxZaFRMMFRx6FmoCWx1nFhcGfycXFi49eR4tXRg9MRI%3D%3AAUuCzIpuUb0jolHQbs6VXcYe0UWnjMkuGFZCVCyVSRg%3D","user":"--"}
{"reqId":"w0sHfwDLvBquB2ZjFaLH","remoteAddr":"IP","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getUID() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Bookmarks\\\\AppInfo\\\\Application->OCA\\\\Bookmarks\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(102): Pimple\\\\Container->offsetGet('BookmarkControl...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(93): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('BookmarkControl...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('BookmarkControl...', 'getBookmarks', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#4 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/bookmarks...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/bookmarks\\\/appinfo\\\/application.php\",\"Line\":59}","level":3,"time":"2016-08-11T11:43:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/bookmarks\/bookmark?type=bookmark&page=0","user":"--"}
```

**Comment by blizzz** [comment]
what's the relation to the news app?

**Comment by thinking-aloud** [comment]
Well, the android bookmark app did not change since 2014 and it causes an error with the bookmark app. Therefore something on the server side must have broken compatibility. 
I also asked the developer of the android app to publish his code, so it can get moved to the current api. It was today, dunno if he will answer though.

**Comment by blizzz** [comment]
Well 9.1 is untested. So, you actually mean Bookmarks app, not news app.

**Comment by thinking-aloud** [comment]
Ups, yes

**Comment by blizzz** [comment]
So the related log entry is apprently

```
#0 \/var\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(113): OCA\Bookmarks\AppInfo\Application->OCA\Bookmarks\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))\
#1 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(102): Pimple\Container->offsetGet('BookmarkControl...')\
#2 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(93): OC\AppFramework\Utility\SimpleContainer->query('BookmarkControl...')\
#3 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\AppFramework\App::main('BookmarkControl...', 'getBookmarks', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\
#4 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)\
#5 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)\
#6 \/var\/www\/owncloud\/lib\/base.php(891): OC\Route\Router->match('\/apps\/bookmarks...')\
#7 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\
#8 {main}\",\"File\":\"\/var\/www\/owncloud\/apps\/bookmarks\/appinfo\/application.php\",\"Line\":59}","level":3,"time":"2016-08-11T11:43:27+00:00","method":"GET","url":"/owncloud/index.php/apps/bookmarks/bookmark?type=bookmark&page=0","user":"--"}
```

apparently when resolving a class (BookmarkController) a parameter was wrongly resolved. There was a change recently, however it added only another parameter, the one referred to in the log was not touched. Ha, rather in the change in instantiation.

@thinking-aloud Take a look at https://github.com/owncloud/bookmarks/commit/ba3d2aeeaf34430b1722e5ec80f6c22b9235583d 

can you change ``$c->query('ServerContainer')->getUserSession()->getUser()->getUID()`` back to ``$c->query('UserId')`` and see whether it works again?

**Comment by thinking-aloud** [comment]
no, unfortunately it did not do the trick.

**Comment by blizzz** [comment]
I just realized that this change went into master only. There were only rather small changes in stable9.1 since 0.8, and of those I do not see any responsible, really.

Which app do you use?

**Comment by blizzz** [comment]
I could not find any relate app on neither f-droid nor 1mobile. 

I have a native Sailfish one however, which correctly fetches the bookmarks.

**Comment by thinking-aloud** [comment]
I use this app:
https://i9195.store.aptoide.com/app/market/cz.nethar.owncloudbookmarks/8/8722126/ownCloud+Bookmarks

**Comment by blizzz** [comment]
@thinking-aloud thank you. I looked into it, the issue resides not within the bookmarks app. There were changes within ownCloud 9.1/Nextcloud 10 that results in this.

What the app tries to accomplish first is to authenticate against the server. This worked up to OC/NC 9, but afterwards the web login URL is different. Since then there is a direct to /login and the app does not handle this. Thus the issue should be reported there.

Given, the apps does what it does because there is no proper API within bookmarks yet, so that it is forced to act in a hackish way. This is a whole different story though…

We cannot do here more, unfortunately.

**Comment by thinking-aloud** [comment]
I started my own app, that uses the API. It can already display the bookmarks and the pages favicon. When the user clicks the bookmark, the page opens in the browser. 
I need to add credential fields, support for editing and storing the bookmarks offline, as well as some async stuff for performance.
With my vacation and the good weather right now, I can't tell, when it will be ready to use. But once it is, I will report back.

**Comment by blizzz** [comment]
> I started my own app, that uses the API. It can already display the bookmarks and the pages favicon. When the user clicks the bookmark, the page opens in the browser. 

That's really cool, but which API? Really there is not other one suited than one just to fetch and display them.

>  With my vacation and the good weather right now, I can't tell, when it will be ready to use. But once it is, I will report back.

By change, you will not be at [Nextcloud conference](https://conf.nextcloud.com), will you?

**Comment by thinking-aloud** [comment]
Well this: https://github.com/owncloud/bookmarks#public-rest-api-json-formatting
I haven't looked into modifying bookmarks jet.
I hat some issues with getting the favicons of the pages async, but that's fixed. Right now I am doing the credential stuff. Problem is, I haven't done and Android development for ages, so it takes some time.

No, I will not be at the Nextcloud conference, although Berlin is not really that far. I'm not familiar with the OC/nextCloud backend. I like using them, but I'm more a java guy and don't care too much for PHP.

**Comment by blizzz** [comment]
> Well this: https://github.com/owncloud/bookmarks#public-rest-api-json-formatting
> edit: https://github.com/owncloud/bookmarks/blob/master/appinfo/routes.php

Ok, right, that's the only API endpoint: https://github.com/owncloud/bookmarks/blob/master/appinfo/routes.php#L41

It does let's you fetch bookmarks, but not add or manipulate them. The bad thing is also, that the password is being passed as GET parameter. It's not an issue with HTTPS itself, but still the parameters get logged by the webserver typically.

There is, however, this PR open https://github.com/owncloud/bookmarks/pull/218 and I thought it has similar issues but on a first, quick glance again, it does not look so bad. I need to look into it again, maybe drive it further, or could try to get a cleaner v2 done. Unfortunately, at the moment I am sick and my current condition does not allow me too exercise (physically or mentally)… *sigh*

> No, I will not be at the Nextcloud conference, although Berlin is not really that far. I'm not familiar with the OC/nextCloud backend. I like using them, but I'm more a java guy and don't care too much for PHP.

Ha, Android client folks will also be there, for instance ;D

**Comment by thinking-aloud** [comment]
Not sending the password in plaintext would be nice too. I could hash it, just store the hash and send it to the server. Then I would not worry to much about the GET anymore.
